# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for Bun (web frontend with SolidJS)
  - package-ecosystem: "npm" # Dependabot uses "npm" for package.json regardless of package manager
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    commit-message:
      prefix: "deps(web)"
      include: "scope"
    groups:
      # Group SolidJS related packages
      solidjs:
        patterns:
          - "solid-*"
          - "@solidjs/*"
        update-types:
          - "minor"
          - "patch"
      # Group Vite and build tools
      build-tools:
        patterns:
          - "vite*"
          - "@vitejs/*"
          - "typescript"
          - "eslint*"
          - "@typescript-eslint/*"
        update-types:
          - "minor"
          - "patch"
      # Group other minor and patch updates
      minor-and-patch:
        patterns:
          - "*"
        exclude-patterns:
          - "solid-*"
          - "@solidjs/*"
          - "vite*"
          - "@vitejs/*"
          - "typescript"
          - "eslint*"
          - "@typescript-eslint/*"
        update-types:
          - "minor"
          - "patch"
      # Keep major updates separate for careful review
      major:
        patterns:
          - "*"
        update-types:
          - "major"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      # Group GitHub Actions updates
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
          - "major"